### PR TITLE
setup and mobile version skeleton

### PR DESCRIPTION
**Pull request by Obote**
### What does this PR do?

- Understand how to parse a Figma design to create a UI.
- Flexbox to place elements in the page.
- Build a personal portfolio site.
- Use images and backgrounds to enhance the look of the website.

### CODE REVIEW

**Review by ZeenatLawal — CHANGES_REQUESTED** [review]
Hi @Obote , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linters that aren't passing.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by Obote** [comment]
Hello @ZeenatLawal, thanks for the feedback. I have checked the errors and everything passes locally on my computer, I have been trying to figure out the same problem with my coding partners who are also having the same error. Any leads to correcting the error would be appreciated.

**Comment by ZeenatLawal** [comment]
> Hello @ZeenatLawal, thanks for the feedback. I have checked the errors and everything passes locally on my computer, I have been trying to figure out the same problem with my coding partners who are also having the same error. Any leads to correcting the error would be appreciated.

It seems you've already resolved it @Obote 😄

**Review by helman101 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️ 🔴 

Hi @Obote 👋, 

You have done an excellent job working on this project 👏 👏👏
but there are still some requirements which aren't been addressed yet.

## To Highlight 🌟 
- You had done a great job passing the linters.
- You used the HTML best practices.

 ## Required Changes ♻️
We are almost there, but in order to complete this part and go ahead with the next project, you have to fix a couple of issues:

- [ ] Please check the comments below 🚀 

## Optional Changes 🤓 
Take a look at these [OPTIONAL] changes to improve your project:

- [ ] please check the comments below for [OPTIONAL] changes

Cheers and Happy coding!👏👏👏

fire

If anything is not 100% clear please leave your questions or comments in the PR thread, we will be glad to help you 😄.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
